################################################################
#
# DOM = Document Object Mapping  
#
# this file contains all the objects mapping of New Kmc
#
# date created: 7.5.17
#
# author: Adi Miller
#
################################################################

'''
@LOGIN
'''
# LOGIN_USER      = "//*[@id=\"username\"]"
LOGIN_USER = "//input[@placeholder='Enter Email']"
LOGIN_PASS = "//input[@placeholder='Enter Password']"
LOGIN_SUBMIT = "//span[text()='Login']"
LOGIN_POP_MSG = "//div[class='kPopupWidget']"
'''
@RESET
'''
FORGOT_PASSWORD = "//a[contains(.,'Forgot Password?')]"
RESET_EMAIL = "//input[@placeholder='Your Email']"
RESET_BUTTON = "//span[@class='p-button-label'][contains(.,'Send')]"
RESET_MESSAGE = "//p[contains(.,'An Email has been sent to your inbox!')]"
NEW_PASSWORD = "//input[@placeholder='Enter new password']"
CONFIRM_PASSWORD = "//input[@placeholder='Confirm new password']"
SEND_PASSWORD = "//span[@class='p-button-label'][contains(.,'Send')]"
SUCCESS_MESSAGE = "//h1[contains(.,'Your new password has been set, please login to Kaltura management console.')]"
'''
@GENERAL
'''
SPINNER = "//div[@class='spinner']"

'''
@ACCOUNT
'''
ACCOUNT_USERNAME = "//div[@class='kUserName']"
CHANGE_ACCOUNT_BUTTON = "//a[contains(text(),'Change Account')]"
ACCOUNT_LOGOUT = "//a[contains(text(),'Logout')]"
CHANGE_ACCOUNT_DIALOG_ROW = "//div[@class='kRow']"
CHANGE_ACCOUNT_DIALOG_LABEL = ".//label[contains(text(),'TEXTTOREPLACE')]"
CHANGE_ACCOUNT_DIALOG_CONTINUE = ".//button[@class='kButtonBranded p-button']"
# CHANGE_ACCOUNT_LANGUAGE         = "//label[@class='ng-tns-c57-3 p-dropdown-label p-inputtext']"
CHANGE_ACCOUNT_LANGUAGE = "//span[contains(@class,'p-dropdown-label p-inputtext')]"
LANGUAGE_MENU_LIST = "//li[contains(@class,'p-dropdown-item p-ripple')]"
CHANGE_ACCOUNT_LANGUAGE_AFTER_PAGE_REFRESH = "//div[@class='ng-tns-c57-3 p-dropdown-label p-inputtext']"
LANGUAGE_MENU_LIST_AFTER_PAGE_REFRESH = "//li[contains(@class,'p-dropdown-item')]"

'''
@CONTENT
'''

CONTENT_TAB = "//a[@class='kMenuLink' and contains(text(),'CONTENT']"
# ENTRIES_TAB = "//div[contains(@href,\"/latest/content/entries\">ENTRIES")]
ENTRIES_TAB = "//a[contains(text(),'ENTRIES')]"
ENTRIES_DROPFOLDER_TAB = "//a[contains(text(),'DROP FOLDERS')]"
CATEGORIES_TAB = "//a[contains(text(),'CATEGORIES')]"
PLAYLISTS_TAB = "//a[contains(text(),'PLAYLISTS')]"
CONTENT_TAB = "//a[contains(text(),'CONTENT')]"
MODERATION_TAB = "//a[contains(text(),'MODERATION')]"

'''
@ENTRIES
'''

#POPUP_MSG = "//div[@class='kPopupWidgetContent']"
POPUP_MSG = "//div[@class='playkit-overlay playkit-error-overlay playkit-active']"
#MSG_CLOSE = "//i[@class='kCloseBtn kIconclose_small']"
MSG_CLOSE = "//i[@class='kCloseBtn kIconclose_small closeBtnInside ng-star-inserted']"
#ENTRIES_TABLE = "//tbody[@class='p-datatable-tbody']"
ENTRIES_TABLE = "//p-table[@datakey='id']"
ENTRY_CHECKBOX = ".//div[contains(@class,'p-checkbox p-component')]"
ENTRY_THUMBNAIL = ".//div[@class='kThumbnailHolder']"
ENTRY_CHECKBOXS = "//div[@class='p-checkbox']"
BULK_ACTIONS = "//button[contains(@class,'kButtonDefault kBulkActionsBtn')]"
SELECTED_ENTRIES = "//tr[@class='p-selectable-row ng-star-inserted p-highlight']"
ENTRIES_FOOTER = "//div[@class='kEntriesTableFooter']"
ENTRIES_DROPDOWN_NUM_OF_ROWS = "//span[contains(@class,'p-dropdown-trigger-icon')]"
# ENTRIES_DROPDOWN_NUM_OF_ROWS    = "//p-dropdown[contains(@class,'p-inputwrapper-filled')]"
ENTRIES_DROPDOWN_LIST = "//ul[contains(@class,'p-dropdown-items')]"
ENTRIES_DROPDOWN_ITEMS = ".//li[contains(@class,'p-dropdown-item p-ripple')]"
ENTRIES_SHOW_ROWS = "//label[@class='p-dropdown-item']"
# ENTRIES_SHOW_ROWS_25            = "//span[text()='25']"
ENTRIES_SEARCH = "//input[@class='kSearchInput p-inputtext ng-pristine ng-valid ng-touched']"
ENTRIES_BULK_DIV = "//div[contains(@class,'kBulkOperations')]"
ENTRIES_FILTER_DIV = "//div[contains(@class,'kFilters')]"
ENTRIES_PAGING_RIGHT = "//span[contains(@class,'p-paginator-icon pi pi-angle-right')]"
ENTRIES_PAGING_LEFT = "//span[contains(@class,'p-paginator-icon pi pi-angle-left')]"
ENTRIES_ACTIVE = "//a[@class='activeLink']"

ENTRY_ROW = ".//tr[contains(@class,'p-selectable-row')]"
ENTRY_ROW_NAME = ".//span[contains(@class, 'kTableColumn') and contains(@class, 'kTitle')]"
ENTRY_ROW_ODD = ".//tr[contains(@class,'p-datatable-odd -content')]"
ENTRY_ROW_EVEN = ".//tr[contains(@class,'p-datatable-even -content')]"
ENTRY_TBL_COLUMN_TITLE = "//th[contains(text(),'Created On')]"
ENTRY_TBL_REFRESH = "//span[@class='p-button-icon kIconrefresh']"
# ENTRY_TBL_DELETE                = "//span[@class='p-button-icon-left kIcontrash']"
ENTRY_TBL_DELETE = "//span[@class='p-button-icon kIcontrash']"
ENTRY_TBL_CONFIRM_DELETE_YES = "//button[@class='p-button']"

ENTRY_ACTIVE_FILTERS = "//div[@class='kTags ng-star-inserted']"
ENTRY_FILTERS_TAG = ".//div[@class='kTagContent ng-star-inserted']"
ENTRY_FILTER_CLEAR_ALL = "//span[@class='kTagsClear ng-star-inserted']"
ENTRY_FILTER_TAG_CLOSE = ".//i[@class='kTagRemove kIconclose_small ng-star-inserted']"
ENTRY_FILTERS_TAG_SCROLL = "//div[@class='kScrollArrows']"
ENTRY_TAGS_RIGHT_SCROLL = "//i[contains(@class,'kIcondropdown_arrow_right kScrollArrow')]"
ENTRY_TAGS_LEFT_SCROLL = "//i[contains(@class,'kIcondropdown_arrow_left kScrollArrow')]"
ENTRY_TABLE_VIDEO_ICON = ".//div[contains(@class,'kIconvideo')]"
ENTRY_TABLE_AUDIO_ICON = ".//div[contains(@class,'kIconaudio')]"
ENTRY_TABLE_IMAGE_ICON = ".//div[contains(@class,'kIconimage')]"
ENTRY_CATEGORIES = "//kautocomplete[@formcontrolname='categories']"
ENTRY_CLIPS = "//div[text()='Clips']"

ENTRY_CLIPS_Trim = "//button[@class='kButtonDefault p-button p-component']"
#EDITOR_FRAME = "//iframe[contains(@src,'https://qa-apache-php7.dev.kaltura.com/apps/kea/')]"
EDITOR_SAVE_A_COPY = "//button[contains(@class, 'save-as-button')]"
CREATE_A_CLIP_COPY = "//button[contains(@class, 'modal-footer-buttons__save')]"
CLIPED_FROM = "//span[contains(@class, 'link')]"
EDITOR_BTN = "//a[text()='Editor']"
SUCCESS_EDITOR_POPUP = "//p-header[contains(text(), ' Success ')]"
CLIP_DURATION = "//span[contains(@class, 'toolbar__total-time')]"
CLIP_TIMELINE = "//div[@class='kea-timeline-stacked-item__overlay kea-timeline-stacked-item__overlay--selected']"
CLIP_START = "//button[@aria-label='Set In']"
CLIP_END = "//button[@aria-label='Set Out']"
CLIP_OK = "//button[contains(@class, 'button modal-footer-buttons__save')]"
CLIP_RESET = "//button[@aria-label='Reset']"
CLIP_RESET_CONTINUE = "//button[contains(@class, 'button--ok')]"
TRIM_SAVE = "//button[contains(@class, 'button--save')]"
TRIM_SAVE_CONFIRM = "//button[contains(@class, 'button modal-footer-buttons__save')]"
TRIM_POPUP = "//p-header[text()='Save']"
# ===============================================================================
# ENTRY_CATEGORIES_LABELS         = ".//span[@class='p-autocomplete-token-label ng-tns-c78-38']"
# ===============================================================================
ENTRY_CATEGORIES_LABELS = "//span[contains(@class, 'p-autocomplete-token-label')]"
ENTRY_TBL_NO_RESULT = "//div[text()='No Results']"
SEARCH_ENTRIES = "//input[contains(@placeholder,'Search')]"
ENTRY_FLAVORS_TAB = "//div[text()='Flavors']"
ENTRY_CONVERTED_FLAVORS = "//span[@class='kFlavorName kTableColumn kConvertedFlavor']"
ENTRY_TYPE_ICON_AUDIO = "//div[@class='kIconsound-small']"
ENTRY_TYPE_ICON_VIDEO = "//div[@class='kIconvideo-small']"
ENTRY_TYPE_ICON_IMAGE = "//div[@class='kIconimage-small']"
ENTRY_TYPE_ICON_LIVE = "//div[@class='kIconlive_transcoding']"
ENTRY_CANCEL_SELECTED = "//a[@class='kAccessControlProfilesCancel']"

# ENTRY PREVIEW SIDE MENU
METADATA = "//div[text()='Metadata']"
THUMBNAILS = "//div[text()='Thumbnails']"
ACCESS_CONTROL = "//div[text()='Access Control']"
SCHEDULING = "//div[text()='Scheduling']"
FLAVORS = "//div[text()='Flavors']"
DISTRIBUTION = "//div[text()='Distribution']"
CAPTIONS = "//div[text()='Captions']"
RELATED_FILES = "//div[text()='Related Files']"
CLIPS = "//div[text()='Clips']"
USERS = "//div[text()='Users']"
ADVERTISEMENTS = "//div[text()='Advertisements']"
FLAVORS_FIRST_MENU = "/html/body/app-root/k-area-blocker/kkmcdashboard/div/kentries/kentry/k-area-blocker/div/div/div[2]/div[2]/kentryflavours/k-area-blocker/div/div[3]/p-table/div/div[1]/div/div[2]/table/tbody/tr[1]/td[10]/div/button"
FLAVORS_PREVIEW = "//span[text()='Preview']"
FLAVORS_PREVIEW_EXIT = "/html/body/kpopupwidget[20]/div/i"

# ENTRY PREVIEW TITLE
METADATA_TITLE = "//span[@class='kSchemaTitle' and text()='Metadata']"
THUMBNAILS_TITLE = "//p[@class='kTitle' and text()='Thumbnails']"
ACCESS_CONTROL_TITLE = "//p[@class='kTitle' and text()='Access Control Profiles']"
SCHEDULING_TITLE = "//p[@class='kTitle' and text()='Scheduling']"
FLAVORS_TITLE = "//p[@class='kTitle' and text()='Flavors']"
DISTRIBUTION_TITLE = "//span[text()='Distribution']"
CAPTIONS_TITLE = "//p[@class='kTitle' and text()='Captions']"
RELATED_FILES_TITLE = "//p[@class='kTitle' and text()='Related files']"
CLIPS_TITLE = "//p[@class='kTitle' and text()='Clips']"
USERS_TITLE = "//p[@class='kTitle' and text()='Users']"
ADVERTISEMENTS_TITLE = "//div[@class='kTitle' and text()='Advertisements']"

'''
@CATEGORY_FILTER
'''
CATEGORY_FILTER = "//div[@class='kCategoriesFilter kDropdown']"
CATEGORY_POP = "//div[@class='kOverrideFAIcons kContainer']"
CATEGORY_CANCEL_EDIT = "//div[contains(@class,'p-dialog p-confirm')]"
CATEGORY_CANCEL_YES_BUTTON = ".//span[text()='Yes']"
CATEGORY_CANCEL_NO_BUTTON = ".//span[text()='No']"
CATEGORY_FIND = "//input[@role='searchbox']"
CATEGORY_PREFFEREMNCES = ""
CATEGORY_FILTER_PREFRENCES_RBTN = ".//label[contains(@class,'p-radiobutton-label')]"
CATEGORY_FILTER_PREFRENCES_BTTNS = "//div[@class='kButtons']"
CATEGORY_ROW_NAME = ".//div[@class='kTitle kTableColumn']"

# CATEGORY_FILTER_PREFRENCES_RBTN = "//div[@class='kButtons']"
CATEGORRY_CLEAR_ALL = "//a[text()='Clear All']"
CATEGORY_AUTO_COMPLETE_LIST = "//span[@class='kHighlightedText']"
# CATEGORY_AUTO_COMPLETE_SELECT   = "//li[@class='p-autocomplete-item p-highlight']"
CATEGORY_AUTO_COMPLETE_SELECT = "//li[contains(@class,'p-autocomplete-item')]"
CATEGORY_AUTO_COMPLETE_RES = ".//li[contains(@class,'p-autocomplete-item')]"  # p-autocomplete-item
CATEGORY_CLOSE = ".//a[@class='kClose']"
CATEGORY_FILTER_PREFERENCES = "//i[@class='kIcongear kTreeConfig']"
CATEGORY_PREFERENCES_POP = "//div[@class='kPopupWidget']"
CATEGORY_PREFERENCES_CLOSE = ".//i[@class='kCloseBtn kIconclose_small closeBtnInside ng-star-inserted']"
CATEGORY_FILTER_WIN = "//div[@class='kPopupWidgetContent ng-star-inserted']"
CATEGORY_TREE_NODE_LINE = ".//div[contains(@class,'p-treenode-content p-treenode-selectable')]"
CATAGORY_TREE_NODE_FATHER = "//li[@class='p-treenode']"
CATEGORY_TREE_NODE = ".//li[contains(@class,'kTreeNodeLabel')]"  # kDisabled
CATEGORY_TREE_NODE_CHILDREN_FRAME = "//ul[@class='p-treenode-children ng-star-inserted']"
CATEGORY_TREE_NODE_CHILDREN = "..//li[contains(@class,'p-treenode p-treenode-leaf')]"
CATEGORY_TREE_NODE_CHILDREN_ISSELECTED = ".//div[contains(@class,'p-treenode-content')]"
CATEGORY_CHECK_BOX = ".//span[contains(@class,'p-checkbox-icon')]"
CATEGORY_TREE_EXPAND = ".//span[contains(@class,'p-tree-toggler-icon pi pi-fw pi-chevron-right')]"
CATEGORY_FILTER_AUTOCOMP_LINE = "//li[contains(@class,'p-autocomplete-item')]"

CATEGORY_FILTER_ERROR_LOADING = ".//div[@class='kLoadingErrorMessage ng-star-inserted']"

'''
@REFINE_FILTER
'''
REFINE_BUTTON = "//div[@class='kRefine kDropdown']"
REFIN_POP = "//div[@class='kOverrideFAIcons kRefineFilters']"
REFINE_SUBJECT_ROW = ".//li[@class='p-treenode ng-star-inserted']"
REFINE_SUBJECT_LABEL = ".//span[@class='kTreeNodeLabel']"
REFINE_EXPAND = ".//span[@class='p-tree-toggler-icon pi pi-fw pi-chevron-right']"
REFINE_LEAF_SUBJECT_ROW = ".//li[@class='p-treenode p-treenode-leaf ng-star-inserted']"
REFINE_GROUP_TITLE = ".//div[contains(@class,'kFiltersGroupTitle')]"
REFINE_NAME = "//span[@class='kTreeNodeLabel ng-star-inserted' and text()='TEXTTOREPLACE']"
REFINE_SEARCH_LANUAGE = "//input[@placeholder='Search']"


'''
@UPLOAD_OBJS
'''
UPLOAD_BTN = "//*[contains(@class,'button')and contains(text(),'Create')]" #"//button[contains(@class,'kButtonDefault kUploadBtn')]"
BULK_UPLOAD = ".//a[text()='Bulk Upload']"
UPLOAD_FROM_DESKTOP = ".//a[text()='Upload from Desktop']"
UPLOAD_FROM_URL = ".//a[contains(text(),'Upload from URL')]"
UPLOAD_ADD_FILE_FA = "div[@class='kAddFile']"
UPLOAD_ADD_FILE = ".//span[text()='Add Files']"
UPLLOAD_FILE_URL = ".//input[contains(@class,'kImportUrl')]"
UPLOAD_SETTINGS_WIN = "//div[@class='kUploadSettings']"
UPLOAD_SETTINGS_ROW = ".//tr[contains(@class,'ng-star-inserted')]"
UPLOAD_SETTINGS_MTYPE_FATHER = ".//div[contains(@class,'p-dropdown p-component')]"
UPLOAD_SETTINGS_DD_MTYPE = "//div[contains(@class,'p-dropdown-trigger')]"
UPLOAD_SETTINGS_TYPE_LIST = ".//ul[@class='p-dropdown-items -content']"
UPLOAD_SETTINGS_TYPE_VIDEO = ".//span[text()='Video']"
UPLOAD_SETTINGS_TYPE_AUDIO = ".//span[text()='Audio']"
UPLOAD_SETTINGS_TYPE_IMAGE = ".//span[text()='Image']"
UPLOAD_SETTINGS_CLOSE = "//i[@class='kCloseBtn kIconclose_small ng-star-inserted']"
UPLOAD_SETTINGS_MSG = "//h1[text()='No files to upload']"
UPLOAD_SETTINGS_DELETE = ".//i[@class='kIcontrash kIconRemoveFile']"
UPLOAD_SETTINGS_EDIT = ".//i[@class='kIconpen kIconEditFileName']"
UPLOAD_EDIT_FILE_NAME = "//input[contains(@class,'kFileNameInput')]"
UPLOAD_FILE_NAME = ".//span[@class='kFileName']"
UPLOAD_MEDIA_TYPE = ".//label[@class='p-dropdown-label p-inputtext']"
# UPLOAD_UPLOAD                   = "//button[@class='kButtonBranded kUploadButton p-button']"
UPLOAD_UPLOAD = "//span[text()='Upload']"
UPLOAD_UPLOAD_BUTTON = "//button[@class='kButtonBranded kUploadButton p-button p-component']"
UPLOAD_SETTIGS_EDIT_FILENAME = ".//input[contains(@class,'kFileNameInput')]"
UPLOAD_SETTINGS_ERROR = ".//i[@class='kIconerror kIconError ng-star-inserted']"
BULK_UPLOAD_ENTRIES = ".//span[@class='p-button-label' and text()='Entries']"
BULK_UPLOAD_CATEGORIES = ".//span[@class='p-button-label' and text()='Categories']"
BULK_UPLOAD_ENDUSERS = ".//span[@class='p-button-label' and text()='End users']"
BULK_UPLOAD_E_USER_ENTIT = ".//span[@class='p-button-label' and text()='End users entitlement']"
BULK_SUCCESS_MESSAGE_WIN = "//div[contains(@class,'kPopupWidgetContent')]"
BULK_SUCCESS_MESSAGE = ".//p[]"
BULK_MSG_LINK_TO_LOAD_PAGE = "//a[contains(text(), 'Bulk Upload Log Page')]"
UPLOAD_TRANSCODING_DROPDOWN = "//p-dropdown[contains(@class,'kTranscodingProfile')]"
UPLOAD_TRANSCODING_ITEM = "//span[contains(@class,'kTranscodingProfileItem') and text()='TEXTTOREPLACE']"
UPLOAD_TRANSCODING_SELECTED_ITEM = "//input[@aria-haspopup='listbox' and @type='text' and @aria-label='TEXTTOREPLACE']"
UPLOAD_CANCEL = "//span[@class='p-button-label' and text()='Cancel']"
PREPARE_VIDEO_ENTRY = ".//a[text()='Video Entry']"
PREPARE_AUDIO_ENTRY = ".//a[text()='Audio entry']"

'''
@ENTRY_PAGE
'''
METADATA_WATCHPERMISSION = "//div[@class='kControl TextArea WatchPermissionRuleControl ng-star-inserted']"
ENTRY_NAME = "//input[@formcontrolname='name']"
ENTRY_DESC = "//textarea[@formcontrolname='description']"
ENTRY_REFERENCEID = "//input[@formcontrolname='referenceId']"
ENTRY_CATEGORIES_FIND = "//kautocomplete[@formcontrolname='categories']"
ENTRY_CATEGORY_FIND_TEXTBOX = ".//input[@class='undefined']"
ENTRY_CATEGORY_SELECTION = "//span[contains(text(),'TEXTTOREPLACE')]"
ENTRY_ACCESS_CONTROL = "//div[text()='Access Control']"
ENTRY_ACCESS_CONTROL_ITEM = "//span[@class='kAccessProfileItem ng-star-inserted' and text()='TEXTTOREPLACE']"
ENTRY_THUMBNAILS_SECTION = "//div[text()='Thumbnails']"
UPLOAD_THUMBNAIL_BUTTON = "//span[@class='p-button-label' and text()='Upload']"
NEXT_ENTRY_BUTTON = "//button[@class='kButtonDefault kNavigationBtnRight p-button p-component p-button-icon-only']"
PREVIOUS_ENTRY_BUTTON = "//button[@class='kButtonDefault kNavigationBtnLeft p-button p-component p-button-icon-only']"
DEUTSCH_SAVE_BUTTON = "//button[@class='kButtonBranded kSaveBtn p-button p-component']"
ENTRY_ID = "//span[@class='kLabel' and text()='ID:']"
CREATION_DATE = "//span[@class='kLabel' and text()='Creation Date:']"
OWNER = "//span[@class='kLabel' and text()='Owner:']"
DURATION = "//span[@class='kLabel' and text()='Duration:']"
MODERATION = "//span[@class='kLabel' and text()='Moderation:']"
PLAYS = "//span[@class='kLabel' and text()='Plays:']"
VIDEO_TYPE = "//div[contains(@class,'kIconvideo-small')]"
AUDIO_TYPE = "//div[contains(@class,'kIconsound-small')]"
IMAGE_TYPE = "//div[contains(@class,'kIconimage-small')]"

'''
@ENTRY_THUMBNAILS
'''
ENTRY_THUMBNAILS = ".//div[contains(text(), 'Thumbnails')]"
THUMBNAIL_SET_AS_DEFAULT = "//a[contains(text(), 'Set as Default')]"
DEFAULT_THUMBNAIL = "//span[contains(text(), 'Default Thumbnail')]"
UPLOAD_THUMBNAIL = "//span[@class='p-button-label' and text()='Upload']"
TUMBNAIL_TABLE = "//div[@class='kTable']"
THUMBNAIL_SIZE = "//th[contains(text(),'Size')]"
THUMBNAIL_DIMENSIONS = "//span[@class='kDimensions']"
THUMBNAIL_DIMENSIONS_UP_DOWN = "//i[contains(@class,'p-sortable-column-icon pi pi-fw pi-sort-amount-')]"
THUMBNAIL_DIMENSIONS_DOWN = "//i[@class='p-sortable-column-icon pi pi-fw pi-sort-amount-down']"
THUMBNAIL_OFFLINE_ERROR_MSG = "//div[@class='kErrorMessageContainer bodyScroll']"
OFFLINE_ERROR_MSG_DISMISS = "//button[@class='' and text()='Dismiss']"

'''
@CATEGORY_PAGE
'''

CATEGORY_ADD = "//button[contains(@class,'kButtonBranded kAddCategoryBtn')]"
CATEGORY_ADD_POPUPWIN = "//div[@class='kPopupWidgetContent ng-star-inserted']"
CATEGORY_NEW_NAME = "//input[@formcontrolname='name']"
CATEGORY_NEW_NO_PARENT = "//label[text()='No Parent']"
CATEGORY_NEW_APPLY = "//span[text()='Apply']"
CATEGORY_NAME = "//input[@formcontrolname='name']"
CATEGORY_DESC = "//textarea[@formcontrolname='description']"
CATEGORY_TAGS = "//input[contains(@class,'ng-tns-c100')]"
CATEGORY_REFERENCE_ID = "//input[@formcontrolname='referenceId']"
CATEGORY_BACK = "//span[@class='p-button-icon kIconarrow_backward']"
CATEGORY_SAVE = "//span[text()='Save']"
CATEGORY_CLOSE_TAG = "//li[contains(@class,'p-autocomplete-token p-autocomplete-token-icon')]"
CATEGORY_METADATA_TAB = "//div[text()='Metadata']"
CATEGORY_SUB_CATEGORIES_TAB = "//div[text()='Sub Categories']"
NEW_CATEGORY_SEARCH = ".//input[@placeholder='Search Categories']"
CATEGORY_TBL_CHECKBOX = "//div[contains(@class,'p-checkbox-box')]"
CATEGORY_PRIVACY_NO_RESTRICTION = "//label[contains(text(),'No Restriction')]"
CATEGORY_PRIVACY_REQUIRE_AUTH = "//label[contains(text(),'Requires Authentication')]"
CATEGORY_PRIVACY_PRIVATE = "//label[contains(text(),'Private')]"
CATEGORY_SAVE_CHANGES = "//span[text()='Save Changes']"
CATEGORY_ENTITLEMENT_SECTION = "//div[text()='Entitlements']"
CATEGORY_ACTIVE_STATE = "//label[@class, 'p-radiobutton p-component p-radiobutton-checked']"
CATEGORY_ATTENTION_MSG = "//span[contains(@class,'p-confirm-dialog-message')]"

'''
@PLAYLISTS_PAGE
'''
PLAYLIST_ADDPLAYLIST_BTN = "//button[contains(@class,'kButtonBranded kAddPlaylistBtn')]"
PLAYLIST_ADD_ENTRY_BTN = "//button[contains(@class,'kButtonBranded kAddEntryBtn')]"
PLAYLIST_ADD_BTN = "//button[@class='p-button p-component kButtonBranded']"
PLAYLIST_CONTENT_SECTION = "//div[contains(text(),'Content')]"
PLAYLIST_DURATION = "//span[contains(text(),'Duration:')]"
PLAYLIST_MANUAL_RDBTN = "//label[text()='Manual  Playlist']"
PLAYLIST_RULEBASED_RDBTN = "//label[text()='Rule-Based Playlist']"
PLAYLIST_ADD_NEW_PLYLST_NAME = "//input[@placeholder='Playlist Name']"
PLAYLIST_ADD_NEW_DESCRIPTION = "//textarea[@placeholder='Description']"
PLAYLIST_CREATE_NEXT_BTN = "//button[contains(@class,'kButtonBranded kNextBtn')]"
PLAYLIST_PAGE_NAME = "//div[text()='NAMETOREPLACE']"
PLAYLIST_SAVE_BTN = "//button[contains(@class,'kButtonBranded kSaveBtn')]"
PLAYLIST_PLUS_BTN = "//button[@label='+']"
PLAYLIST_ROW_ACTIONS = ".//div[@class='kPlaylistEntriesTableActions']"
MOVE_UP = "//span[contains(text(),'Move Up')]"
MOVE_DOWN = "//span[contains(text(),'Move Down')]"
MOVE_TO_TOP = "//span[contains(text(),'Move to Top')]"
MOVE_TO_BOTTOM = "//span[contains(text(),'Move to Bottom')]"
PLAYLIST_NAME_COL_UP_DOWN = "//i[contains(@class,'p-sortable-column-icon pi pi-fw pi-sort-')]"
# PLAYLIST_ENTRIES_NAMES          = "//span[@class='kTitle kTableColumn']"

PLAYLIST_NAME_TITLE_AFTER_CLICK = "//th[@class='p-sortable-column p-highlight']"
PLAYLIST_NAME_COL_TITLE = "//th[@class='p-sortable-column']"
PLAYLIST_ID_DETAILS_BAR = "//span[@class='kLabel' and text()='ID:']/following-sibling::span[@class='']"
PLAYLIST_ID_PLAYLISTS_TABLE = "//span[@class='kTableColumn']"
PLAYLIST_TABLE_ROW = "//tr[@class='p-selectable-row']"
PLAYLIST_NAME = "//div[@class='kTitle']"
PLAYLISTS_ACTIONS_BUTTON = "//button[@class='kMoreActionsButton p-button p-button-icon-only']"
PLAYLIST_NAME_SHARE_EMBED = "//div[@class='kParamsContainer']/descendant::span[@class='kTitle']"
ENTRY_TITLE_SHARE_EMBED = "//span[@class='k-title']"
SHARE_EMBED_PLAYER_IFRAME = "//iframe[@class='mwEmbedKalturaIframe']"
SHARE_EMBED_BIG_IFRAME = "//iframe[@class='']"

'''
@ADMINISTRATION
'''

ADMIN_MAIN = "//i[contains(@class,'kIconuser')]"
ADMIN_USERS_TAB = "//div[@class='subMenuContainer kLeft' and text()='USERS']"
ADMIN_ROLES_TAB = "//div[@class='subMenuContainer kLeft' and text()='ROLES']"
ADMIN_MORE_USERS_MSG = "//div[@class='kUsersNeedMore']"
ADMIN_MORE_USERS_CURRENT = "//span[@class='kCurrentStatus']"
ADMIN_USERS_ROW_NAME = ".//span[@class='kTableColumn kFullName']"
ADMIN_USERS_ROW_USERDETAIL = ".//span[@class='kTableColumn']"

USERS_ADD_USER = ".//span[@class='p-button-label' and text()='Add User']"
ROLES_ADD_ROLE = ".//span[@class='p-button-label' and text()='Add Role']"
ADD_USER_MODAL_ROW = "//div[@class='kRow kValign']"
ADD_USER_MODAL_LABEL = ".//span[contains(@class,'kLabel')]"
ADD_USER_MODAL_INPUT = ".//div[@class='kControl']/input[@type='text']"
USER_INPUT_ERROR_EMAIL = ".//span[@class='kLabel' and text()='Login Email address']/following-sibling::div[@class='kRequired kHasError']"
USER_INPUT_ERROR_FIRST_NAME = ".//span[@class='kLabel' and text()='First Name']/following-sibling::div[@class='kRequired kHasError']"
USER_INPUT_ERROR_LAST_NAME = ".//span[@class='kLabel' and text()='Last Name']/following-sibling::div[@class='kRequired kHasError']"
ADMIN_USERS_TBL_ROW = ".//tr[@class='ng-star-inserted']"
ADD_EXISTING_USER_ALERT_TITLE = "//span[@class='p-dialog-title' and text()='User already exists']"
ADD_EXISTING_ALERT_YES = "//span[@class='p-button-label' and text()='Yes']"
ADD_EXISTING_ALERT_NO = "//span[@class='p-button-label' and text()='No']"
ADMIN_USER_INFO = "//span[text()='TEXTTOREPLACE']"
USERS_ROW_ACTIONS = ".//div[@class='kUsersTableActions']"
USERS_ROW_ACTION_DELETE = "//span[@class='p-menuitem-text ng-star-inserted' and text()='Delete']"
USERS_ROW_ACTION_EDIT = "//span[@class='p-menuitem-text ng-star-inserted' and text()='Edit']"
USERS_ROW_ACTION_BLOCK_UNBLOCK = "//span[@class='p-menuitem-text ng-star-inserted' and text()='Block / Unblock']"

'''
@DISTRIBUTION
'''

DISTRIBUTION_TAB = "//div[contains(text(),'Distribution')]"
DISTRIBUTION_CHECKBOX_SELECTION = "//span[contains(text(),'TEXTTOREPLACE')]"
DISTRIBUTION_EXPORT_BUTTON = "//button[@class='kButtonBranded p-button p-component']"
DISTRIBUTION_EXPORT_UPDATE_BUTTON = "//span[contains(text(),'Export')]"
DISTRIBUTION_REFRESH_STATUS = "//span[@class='p-button-icon kIconrefresh']"
DISTRIBUTION_STATUS = "//span[@class='kStatus ng-star-inserted']"
TVM_LOGIN_USER = "//input[@name='name']"
TVM_LOGIN_PASS = "//input[@name='password']"
TVM_LOGIN = "//input[@class='signUp']"
TVM_KALTURA_MUS_PRIMARY = "//td[contains(text(),'Kaltura Mus - Primary')]"
TVM_INNER_GROUPS = ".//a[text()='Inner groups']"
TVM_KALTURA_MUS_PRIMARY_PAGE2 = "//td[contains(text(),'Kaltura Mus Regular')]"
TVM_BROWSE_AS = ".//a[text()='Browse as']"
TVM_ENTRY_NAME = "//td[contains(text(),'TEXTTOREPLACE')]"
TVM_FILES = ".//a[text()='Files']"
FACEBOOK_LOGIN_USER_UK = "//input[@placeholder='Email address or phone number']"
FACEBOOK_LOGIN_USER_US = "//input[@placeholder='Email or phone number']"
FACEBOOK_LOGIN_PASS = "//input[@placeholder='Password']"
FACEBOOK_LOGIN_US = "//button[text()='Log In']"
FACEBOOK_LOGIN_UK = "//button[text()='Log in']"
FACEBOOK_ENGLISH = "//a[text()='English (US)']"
FACEBOOK_FILE_DESCRIPTION = "//*[contains(text(),'TEXTTOREPLACE')]"
FACEBOOK_AUTHENTICATION_LOGIN_USER = "//input[@name='email']"
FACEBOOK_AUTHENTICATION_LOGIN_PASS = "//input[@name='password']"
FACEBOOK_AUTHENTICATION_LOGIN_BTN = "//button[text()='Login']"
FACEBOOK_AUTHENTICATION_PROCEED = "//a[text()='Proceed to Facebook for authorization']"
FACEBOOK_AUTHENTICATION_CONTINUE_AS_BTN = "//span[text()='Continue as Alex Kaltura']"
FACEBOOK_AUTHENTICATION_RESULT = "//*[@id='wrap']"
FACEBOOK_AUTHENTICATION_SITE_LOGIN_USER = "//input[@name='email']"
FACEBOOK_AUTHENTICATION_SITE_LOGIN_PASS = "//input[@name='pass']"
FACEBOOK_AUTHENTICATION_SITE_LOGIN = "//button[@name='login']"

'''
@SYNDICATION
'''
SYNDICATION_TAB = "//a[contains(text(),'SYNDICATION')]"
SYNDICATION_ADDFEED_BTN = "//button[@class='kButtonBranded kAddFeedBtn p-button p-component']"
SYNDICATION_ALLCONTENT_RDB = "//label[text()='All Content']"
SYNDICATION_PLAYLISTCONTENT_RDB = "//label[text()='From Playlist']"
SYNDICATION_NAME = "//input[@formcontrolname='name']"
SYNDICATION_MAIN_BTN = "//div[@class='kFeedDetailsContainerHeader']"
SYNDICATION_CANCEL_BTN = ".//a[@class='kBulkCancel']"
SYNDICATION_PLAYLIST_SEARCHDROPDOWN = "//ksearchabledropdown[@formcontrolname='selectedPlaylist']"
SYNDICATION_PLAYLIST_CHECKBOX_SELECTION = "//span[contains(text(),'TEXTTOREPLACE')]"
SYNDICATION_PLAYLIST_SELECTION_INSERT = "//div[@class='kPlaylist ng-star-inserted']"
SYNDICATION_DESTINATION_MAIN = "//span[text()='Choose Destination']"
SYNDICATION_DESTINATION_CHECKBOX_SELECTION = "//span[contains(text(),'TEXTTOREPLACE')]"
SYNDICATION_LANDINGPAGE = "//input[@formcontrolname='landingPage']"
SYNDICATION_SAVE_BTN = "//button[@class='kSaveBtn kButtonBranded p-button p-component']"
SYNDICATION_CONTENTFLAVOR_MAIN = "//label[text()='Source']"
SYNDICATION_CONTENTFLAVOR_CHECKBOX_SELECTION = ".//span[contains(text(),'TEXTTOREPLACE')]"
SYNDICATION_ADD_DEFAULT_TRANSCODINGPROFILE = "//p-checkbox[@formcontrolname='addToDefaultTranscodingProfile']"
SYNDICATION_PLAYER_MAIN_SELECTION = "//p-dropdown[@formcontrolname='selectedPlayer']"
SYNDICATION_PLAYER_CHECKBOX_SELECTION = ".//span[contains(text(),'TEXTTOREPLACE')]"
SYNDICATION_PLAYBACK_FROMGOOGLE = "//label[text()='From Google']"
SYNDICATION_PLAYBACK_LINKBACKTOMYSITE = "//label[text()='Linkback to my site']"
SYNDICATION_ADULTCONTENT = "//p-checkbox[@formcontrolname='adultContent']"
SYNDICATION_NAME_TABLE = "//div[contains(text(),'TEXTTOREPLACE')]"
SYNDICATION_DESTINATION_EDIT = "//label[contains(text(),'TEXTTOREPLACE')]"
SYNDICATION_ADULTCONTENT_CHECKBOX = ".//div//div[2]//span"
SYNDICATION_ADD_DEFAULT_TRANSCODINGPROFILE_CHECKBOX = ".//div//div[2]//span"
SYNDICATION_DELETE_BTN = "//button[@class='kDeletehBtn kButtonDanger p-button p-component ng-star-inserted']"
SYNDICATION_URL = "//input[@class='kElipsis kUrl p-inputtext p-component p-filled']"
SYNDICATION_DLT_CONFIRM_DELETE_YES = "//span[text()='Yes']"
SYNDICATION_ID = "//div[@class='kColId']"

'''
@TAGS
'''

TAGS_ADD_TAGS_NAME = "//input[@role='searchbox']"
TAGS_ADD_TAGS_AUTOCOMPLETE_ITEM = "//li[contains(@class,' p-autocomplete-item')]"
TAGS_ADD_TAGS_SAVE_CHANGES = "//span[text()='Save Changes']"

'''
@TBL
'''
TBL_MORE_ACTIONS = ".//button[@class='kMoreActionsButton p-button p-component p-button-icon-only']"
TBL_ACTION_MENUE = "//span[contains(@class,'p-menuitem-text ng-star-inserted')]"
TBL_BULK_ACTIONS = "//span[text()='Bulk Actions']"
TBL_STATUS_CELL = "//div[@class='kStatusWrap']"

'''
@GLOBAL_OBJECTS
'''

GLOBAL_SAVE = "//span[text()='Save']"
POPUP_WIN_ADD_TAGS = "//div[@class='kPopupWidgetContent ng-star-inserted']"
POPUP_WIN = "//form[@class='kContainer ng-dirty ng-valid ng-touched']"
TAGS_LABLE = ".//span[@class='p-autocomplete-token-label']"
GLOBAL_YES_BUTTON = ".//span[text()='Yes']"
GLOBAL_NO_BUTTON = ".//span[text()='No']"
GLOBAL_ERROR_CANCEL_BUTTON = "//button[@class='ng-star-inserted']"
GLOBAL_ERROR_POPUP_MSG_TEXT = "//div[@class='kErrorMessageText']"
GLOBAL_ERROR_POPUP_MSG_TITLE = "//div[@class='kErrorMessageTitle']"
POPUP_MESSAGE = "//div[contains(@class,'p-dialog p-confirm-dialog')]"
POPUP_MESSAGE_OK = ".//span[@class='p-button-label' and text()='OK']"
POPUP_APPROVE_MSG = "//button[@class='kButtonBranded p-button']"
CLOSE_WELCOME_MSG = "//a[contains(text(),'Close')]"
GLOBAL_TABLE_HEADLINE = "//tr[@class='ng-star-inserted']"
POPUP_MESSAGE_YES = "//span[@class='p-button-label' and text()='Yes']"
POPUP_MESSAGE_NO = "//span[@class='p-button-label' and text()='No']"
DROPDOWN_NARROW_FATHER = ".//div[contains(@class,'p-dropdown-items-wrapper')]"
DROPDOWN_BTN_FATHER = "//p-dropdown[@formcontrolname='selectedEmbedType']"
DROPDOWN_BTN = ".//div[@class='p-dropdown-trigger']"

'''
@SETTINGS
'''
SETTINGS_BUTTON = "//i[contains(@class,'kIcongear ng-star-inserted')]"

CUSTOM_DATA_TAB = "//a[contains(text(),'CUSTOM DATA')]"
ADD_CUSTOM_SCHEMA_BUTTON = "//span[@class='p-button-label' and text()='Add Custom Schema']"
CUSTOM_SCHEMA_TITLE = "//input[@class='kControl p-inputtext p-component ng-untouched ng-pristine ng-invalid']"
ADD_CUSTOM_FIELD_BUTTON = "//span[@class='p-button-label' and text()='Add Custom Field']"
FIELD_TYPE_DROPDOWN = "//div[contains(@class,'p-dropdown-trigger')]"
FIELD_TYPE_SELECT_LIST = "//p-dropdownitem[contains(@class,'ng-star-inserted')]"
FIELD_TYPE_SELECT_LIST_ITEM = "//p-dropdown[contains(@class,'ng-tns-c57-')]" #"//p-dropdown[contains(@class,'ng-tns-c57-')]"
ADD_CUSTOM_SCHEMA_SAVE_BUTTON = "//span[@class='p-button-label' and text()='Save']"
ADD_CUSTOM_SCHEMA_TBL_FIELDS ="//div[@class='kSchemaTableWrapper']"
FIELD_LABEL = "//input[@class='kControl ng-untouched ng-pristine ng-invalid p-inputtext p-component']"
ADD_BUTTON_CUSTOM_FIELD = "//span[@class='p-button-label' and text()='Add']"
LIST_VALUES_TEXTBOX = "//textarea[@class='kControl kTextArea ng-untouched ng-pristine ng-valid p-inputtext p-component']"
TAB_ACCESS_CONTROL = "//a[contains(text(),'ACCESS CONTROL')]"
TAB_MY_USER_SETTINGS = "//a[contains(text(),' MY USER')]"
MY_USER_NAME_SETTINGS = "//i[@class='kIconpen']"
MY_USER_FIRST_LAST_NAME_INPUT = "//input[contains(@class,'kControl p-inputtext p-component')]"
CHECK_USER_NAME = "//span[contains(text(),'TEXTTOREPLACE')]"
TAB_TRANSCODING_SETTINGS = "//a[contains(text(),' TRANSCODING')]"
EDIT_USER_INPUT_ERROR_FIRST_NAME = "//div[@class='kLabel' and text()='First Name']/following-sibling::div[@class='error']"
EDIT_USER_INPUT_ERROR_LAST_NAME = "//div[@class='kLabel' and text()='Last Name']/following-sibling::div[@class='error']"
EDIT_USER_NAME_INPUT_ERROR_PASSWORD = "//div[@class='error ng-star-inserted' and text()=' This field is required. ']/following-sibling::div[@class='kPasswordRequired' and text()='* Password is required for editing your Name. ']"
MY_USER_SETTINGS_MODAL_INPUT = "//input[contains(@class, 'kControl')]"
#MY_USER_SETTINGS_PASSWORD_INPUT = "//input[contains(@class, 'kControl p-inputtext ng-untouched ng-pristine ng-invalid')]"
MY_USER_SETTINGS_PASSWORD_INPUT = "//input[@type='password']"
EDIT_PASSWORD = "//a[contains(text(),'Edit Password')]"
CHANGE_USER_PASSWORD_ERROR_CURRENT = "//div[@class='error ng-star-inserted' and text()=' This field is required. ']"
REACH_TAB = "//a[contains(text(),' REACH')]"
REACH_TAB_JS = "document.querySelector('#appMenu > kkmcappmenu > div > div > kkmcappcontentmenu:nth-child(1) > div:nth-child(4) > a').click()"
PROFILE_COUNT = "//span[@class='kTotalProfilesCount ng-star-inserted']"
REACH_LANGUAGE1 = "//li[@aria-label='TEXTTOREPLACE']"
REACH_LANGUAGE = "//span[text()='TEXTTOREPLACE']"
REACH_PROFILE_NAME = "//div[@class='kReachProfileName kTableColumn' and contains(text(),'TEXTTOREPLACE')]"
REACH_PROFILE_NAME_INPUT = "//input[contains(@class,'p-inputtext p-component ng-')]"
REACH_PROFILE_MENU_SETTINGS_ERROR = "//div[@class='kSectionHasErrors']"
REACH_SERVICE_PARAMETERS = "//div[contains(text(),' Service Parameters')]"
REACH_PROFILE_MAX_CHARACTERS_INPUT = "//input[contains(@class,'ng-pristine ng-valid p-inputtext p-component p-filled')]"
REACH_PROFILE_SLIDER = "//span[@class='p-inputswitch-slider']"
REACH_DROP_DOWN_MENU = "//div[contains(@class,'p-dropdown-label-container')]"

'''
@ACCESS_CONTROL
'''
ACCESS_CONTROL_ADD_PROFILE = "//span[contains(text(),'Add Profile')]"
ACCESS_CONTROL_PROFILE_NMAE = "//input[@class='kControl p-inputtext p-component ng-untouched ng-pristine ng-invalid']"
ACCESS_CONTROL_PROFILE_DESC = "//textarea[@class='kControl p-inputtext p-component ng-untouched ng-pristine ng-valid']"
ACCESS_CONTROL_SELECTED_DOMAINS_RBTN = "//label[contains(text(),'Selected Domains Only')]"
ACCESS_CONTROL_BLOCK_DOMAINS_RBTN = "//label[contains(text(),'Block Selected Domains')]"
ACCESS_CONTROL_RBTN_GLOB = "//label[contains(text(),'TEXTTOREPLACE')]"
ACCESS_CONTROL_DOMAINS_INPUT = ".//input[contains(@class,'ng-tns-c100-')]"
ACCESS_CONTROL_ADD_ROWS = "//div[@class='kRow']"
COUNTRIES_LIST_DROP_DOWN_BTN = "//span[contains(@class,'p-multiselect-trigger-icon')]"
COUNTRIES_LIST_FILTER_TXT = "//input[@placeholder='Find Country']"
COUNTRIES_CHECKBOX = "//li[@class='p-multiselect-item p-ripple']"
SAVE_BTN = "//span[text()='Save']"
ACCESS_CONTROL_PROFILE_NAME_TBL = ".//span[@class='kAccessControlProfileTableName kTableColumn']"

'''
@TRANSCODING_SETTINGS
'''
TRANSCODING_ADD_PROFILE = "//span[contains(text(),'Add Profile')]"
TRANSCODING_ADD_NAME = "//input[@placeholder='Profile Name']"
TRANSCODING_ADD_DESCRIPTION = "//input[@placeholder='Profile Description']"
TRANSCODING_ADD_METADATA = "//input[@placeholder='Entry ID']"
TRANSCODING_ADD_SAVE_BUTTON = "//span[@class='p-button-label' and text()='Save']"
TRANSCODING_NEW_ID = "//span[text()='new']"
TRANSCODING_PROFILE_TITLE = "//div[@class='kTitle' and contains(text(),'TEXTTOREPLACE')]"
TRANSCODING_FLAVOR_CHECKBOX = "//tr[.//td[.//div[contains(text(),'TEXTTOREPLACE')]]]//div[@class='p-checkbox p-component']"
TRANSCODING_ICON = "//div[@class='kIcon kIcontranscoding ng-star-inserted']"
TRANSCODING_LIVEICON = "//div[@class='kIcon kIconlive_transcoding ng-star-inserted']"
TRANSCODING_ADD_ERR_POPUP = "//span[@class='p-dialog-title' and text()='Attention']"
TRANSCODING_POPUP_YES_BUTTON = "//span[@class='p-button-label' and text()='Yes']"
TRANSCODING_POPUP_NO_BUTTON = "//span[@class='p-button-label' and text()='No']"
TRANSCODING_TABLE = "//div[@class='kTranscodingProfilesList']"
TRANSCODING_BACKWARD_BUTTON = "//span[contains(@class,'kIconarrow_backward')]"
TRANSCODING_ROW = ".//tr[@class='p-selectable-row ng-star-inserted']"
TRANSCODING_ROW_ACTIONS = ".//div[@class='kTranscodingProfilesTableActions']"
#TRANSCODING_ROW_NAME = ".//div[@class='kTableColumn kTranscodingProfileName ng-star-inserted']"
TRANSCODING_ROW_NAME = ".//div[contains(@class,'kTableColumn')]"
TRANSCODING_ROW_ACTION_DELETE = "//span[@class='p-menuitem-text ng-star-inserted' and text()='Delete']"
TRANSCODING_ROW_ACTION_EDIT = "//span[@class='p-menuitem-text' and text()='Edit']"
TRANSCODING_ROW_ACTION_SET_AS_DEFAULT = "//span[@class='p-menuitem-text ng-star-inserted' and text()='Set As Default']"
TRANSCODING_DEFAULT_PROFILE = "//span[@class='kTranscodingProfileNameDefault']"
TRANSCODING_ROW_CHECKBOX = ".//tr[.//td[.//div[contains(text(),'TEXTTOREPLACE')]]]//div[@class='p-checkbox p-component']"
TRANSCODING_ROW_ID = ".//tr[.//td[.//div[contains(text(),'TEXTTOREPLACE')]]]/td[4]"
TRANSCODING_ROW_NAME_BY_ID = ".//tr[.//td[text()='TEXTTOREPLACE']]/td[2]/div/div"
TRANSCODING_BULK_DELETE = "//span[@class='p-button-icon kIcontrash']"
TRANSCODING_DELETE_POPUP = "//div[@class='kErrorMessageTitle' and text()='Delete Profiles']"
TRANSCODING_DELETE_POPUP_YES = "//button[text()='Yes']"
TRANSCODING_DELETE_POPUP_NO = "//button[text()='No']"
TRANSCODING_UPDATE_ID = "//span[text()='TEXTTOREPLACE']"
TRANSCODING_UPDATE_DESCRIPTION = "//textarea[@placeholder='Profile Description']"
TRANSCODING_FLAVOR_NAME_SELECTED = "//tr[@class='p-selectable-row p-highlight ng-star-inserted']//div[@class='kTitle kTableColumn']"
TRANSCODING_ERROR_MSG = "//span[text()='Error']"
TRANSCODING_SOURCE_FLAVOR_NAME = "//div[@class='kTitle kTableColumn' and text()='Source ']"
TRANSCODING_FLAVOR_NAME = "//div[@class='kTitle kTableColumn' and text()='TEXTTOREPLACE']"
TRANSCODING_EDIT_FLAVOR_SETTINGS = "//i[@class='kIconEdit kEditFlavorIcon']"
IMPACT_ON_ENTRY_READINESS = "//span[contains(@class,'p-dropdown-label p-inputtext ng-star-inserted') and text()='No Impact']"
IMPACT_ON_ENTRY_READINESS_LIST_ITEMS = "//p-dropdownitem[contains(@class,'ng-star-inserted')]"
FLAVOR_GENERATION_POLICY = "//span[contains(@class,'p-dropdown-label p-inputtext ng-star-inserted') and contains(text(),'Optimization')]"
FLAVOR_GENERATION_POLICY_LIST_ITEMS = "//p-dropdownitem[contains(@class,'ng-star-inserted')]"
INTERMEDIATE_FLAVOR_HANDLING = "//span[contains(@class,'p-dropdown-label p-inputtext ng-star-inserted') and text()='Keep Flavor']"
INTERMEDIATE_FLAVOR_HANDLING_POLICY_LIST_ITEMS = "//p-dropdownitem[contains(@class,'ng-star-inserted')]"

'''
@MODERATION
'''

MODERATION_APPROVE_MSG = "//span[contains(@class,'p-dialog-title') and text()='Moderation: Approve Media']"
MODERATION_REJECT_MSG = "//span[contains(@class,'p-dialog-title') and text()='Moderation: Reject Media']"
MODERATION_PLAYER_WINDOW = "//div[@class='kEntryReportWrap kOverrideFAIcons']"
MODERATION_CANCEL = "//a[@class='cancelLink' and text()='Cancel']"
MODERATION_YES_BUTTON = "//span[@class='p-button-label' and text()='Yes']"
MODERATION_APPROVE_ENTRY = "//span[@class='p-button-label' and text()='Approve Entry']"
MODERATION_REJECT_ENTRY = "//span[@class='p-button-label' and text()='Reject Entry']"

'''
@PLAYER
'''
VIDEOIFRAME = "//iframe[contains(@src,'https://www.kaltura.com/')]"
VIDEOIFRAMETESTING = "//iframe[contains(@src,'https://qa-apache-php7.dev.kaltura.com/')]"
PLAYBTN = "//button[@class='btn comp playPauseBtn display-high icon-play']"
BIG_PLAYBTN = "//a[@class='icon-play  comp largePlayBtn  largePlayBtnBorder']"
FULLSCREENBTN = "//button[@class='btn comp fullScreenBtn pull-right display-high icon-expand']"
SHAREEMBED = "//a[text()='Share & Embed']"
PREVIEWEMBEDLINK = "//a[contains(@href,'/tiny/')]"
PLAYBTNV3_PROD = "//button[@class='playkit-pre-playback-play-button']"
PLAYBTNV3_TESTING = "//button[@class='playkit-pre-playback-play-button']"
MSG_ON_PLAYER = "//div[@class='alert-message alert-text error']"
MSG_ON_PLAYERV7 = "//div[@class='playkit-headline']"

'''
@PRVIEW_EMBED
'''
ADVANCED_SETTINGS_LINK = "//a[contains(text(),'Advanced Settings')]"
PREVIEWANDEMBED_EMBEDTYPE = "//span[text()='TEXTTOREPLACE']"
PREVIEWANDEMBED_HTTPS = "//p-inputswitch[@formcontrolname='secured']"
PREVIEWANDEMBED_HTTPS_STATUS = ".//input[@type='checkbox']"
PREVIEWANDEMBED_EMBEDTYPE_DROPDOWN_BTN = "//div[@class='p-dropdown-trigger']"
PREVIEWANDEMBED_SELECTPLAYER_FATHER = "//div[@class='playerItem selectedPlayer ng-star-inserted']"
PREVIEWANDEMBED_SELECT_PLAYER = "//span[text()='TEXTTOREPLACE']"
PREVIEWANDEMBED_CLOSE_BTN = "//i[@class='kIconclose_small kClose']"
PREVIEWANDEMBED_SELECT_EMBERD_TYPE = "//p-dropdown[@formcontrolname='selectedEmbedType']"

'''
@ADMIN_CONSOLE
'''
MACONSOLE_LOGIN_USER = "//input[@id='email']"
MACONSOLE_LOGIN_PASS = "//input[@id='password']"
MACONSOLE_LOGIN_LOGIN = "//span[text()='Login']"
MACONSOLE_ENTRIES_TAB = "//table[@class='clear']"
MACONSOLE_ACTIONS = "//select[@class='options']"
MACONSOLE_LIST_OPTIONS = ".//option[text()=TEXTTOREPLACE]"
MACONSOLE_ADDNEWACCOUNT_TAB = ".//a[text()='Add New Account']"
MACONSOLE_USAGEREPORT_TAB = ".//a[text()='Usage Reports']"
MACONSOLE__USAGEREPORT_TABLE = "//div[@id='resultsSubs']"
MACONSOLE__USAGEREPORT_TABLE_ACCOUNTSNAME = ".//td[text()='TEXTTOREPLACE']"
ADMINCONSOLE_PUBLISHER_ID = "//option[@label='Publisher ID']"
ADMINCONSOLE_FILTER_TEXT = "//input[@name='filter_input']"
ADMINCONSOLE_SEARCH_BTN = "//button[@name='cmdSubmit']"
ADMINCONSOLE_PAGE_SIZE = "//select[@id='pageSize']"
ADMINCONSOLE_PAGE_100 = "//option[text()='100']"
ADMINCONSOLE_MALOGIN_OPTION = "//option[@value='mpLogin']"
MACONSOLE_ADDNEWACCOUNT_ADMINNAME = "//input[@name='admin_name']"
MACONSOLE_REACH_TAB = ".//a[text()='Reach']"
MACONSOLE_REACH_PROFILES = ".//a[text()='Reach Profiles']"
BATCH_PROCESS_CONTROL = "//a[contains(.,'Batch Process Control')]"
BATCH_SEARCH_ENTRY_INPUT = "//input[@id='entryId']"
BATCH_SEARCH_ENTRY_BUTTON = "//button[@id='search']"

'''
@ADMIN_CONSOLE_REACH
'''
ADMINCONSOLE_REACH_PROFILES_TABLE = '//*[@id="reach_profile_list_div"]/table/tbody/tr[*]/td[2]'
ADMINCONSOLE_REACH_PROFILE_CONFIG = '//*[@id="reach_profile_list_div"]/table/tbody/tr[*]/td[10]/select/option[2]'
ADMINCONSOLE_REACH_PROFILE_NEW = "//input[@value='test-boolean new']"
ADMINCONSOLE_REACH_PROFILE_DELITION = "//option[@label='DELETE_AFTER_THREE_MONTHS']"
ADMINCONSOLE_REACH_PROFILE_MODERATION = "//select[@name='enableMachineModeration']/option[@label='TRUE']"
ADMINCONSOLE_REACH_PROFILE_REGION = "//select[@name='vendorTaskProcessingRegion']/option[@label='EU']"
PARTNER_ID = "//*[contains(text(),'PID')]"

'''
@MEDIA_REPURPOSING_PROFILE
'''
ADMINCONSOLE_MR_OPTION = "//option[@value='listMediaRepurposing']"
ADMINCONSOLE_MR_DO_FILTER = "//button[@id='do_filter']"
ADMINCONSOLE_MR_DRYRUN_MRID = "//select[contains(@onchange,'TEXTTOREPLACE')]//option[contains(text(),'Execute Dry-Run')]"
ADMINCONSOLE_MR_DRYRUN_ID = "//input[@name='dryRunId']"
ADMINCONSOLE_MR_DRYRUN_GETLOG_BTN = "//button[@name='getDryRunLogSubmit']"
ADMINCONSOLE_MR_DRYRUN_LOG = "//div[@class='error']"
ADMINCONSOLE_MR_DRYRUN_LOG_LESS1000 = "//label[@for='dryRunTitle']"
ADMINCONSOLE_MR_DRYRUN_LOG_CLOSE_BTN = "//span[@class='ui-icon ui-icon-closethick']"
ADMINCONSOLE_MR_DRYRUN_LOG_PAGINATOR = "//div[@class='paginator']"
ADMINCONSOLE_MR_OPTIONS = ".//select[@class='options']"
ADMINCONSOLE_MR_ACTION = ".//option[@value='TEXTTOREPLACE']"
MR_FILTER_TYPE = "//select[@id='filter_type']"
MR_CHOOSE_TEMPLATE = "//select[@id='template']"
MR_SET_TEMPLATE = "//option[@label='TEXTTOREPLACE']"
MR_CREATE_BTN = "//button[@id='submit']"
MR_NAME = "//input[@id='media_repurposing_name']"
MR_MAX_ENTRIES = "//input[@id='max_entries_allowed']"
MR_CREATED_AT_LESS_THAN_OR_EQUAL = "//input[@id='FilterParams_createdAtLessThanOrEqual']"
MR_EXPAND_FILTER = "//button[@id='expandFilter']"
MR_ENTRY_NAME_LIKE = "//input[@id='FilterParams_nameLike']"
MR_MAIL_TO = "//input[@name='mailTo']"
MR_MAIL_SENDER = "//input[@name='sender']"
MR_MAIL_SUBJECT = "//input[@name='subject']"
MR_MAIL_MESSAGE = "//textarea[@name='message']"
MR_MAIL_FOOTER = "//textarea[@name='footer']"
MR_ENTRY_LINK = "//input[@name='link']"
MR_PLAYED_LESS_OR_EQUAL = "//input[@id='FilterParams_lastPlayedAtLessThanOrEqual']"
MR_PLAYED_LESS_OR_NULL = "//input[@id='FilterParams_lastPlayedAtLessThanOrEqualOrNull']"
MR_TASK_TIME = "//input[@id='mr_task_0-taskTime']"
MR_SAVE_BTN = "//span[text()='Save']"
MR_ROOT_ENTRYID_EQUAL = "//input[@name='FilterParams_rootEntryIdIn']"
MR_ENTRYID_EQUAL = "//input[@name='FilterParams_idEqual']"
MR_SEARCH_BTN = "//button[@name='cmdSubmit']"
MR_PROFILE_LOGS_ENTRY_DATA = "//td[contains(text(),'TEXTTOREPLACE')]"
MR_PROFILE_LOGS_PAGINATOR = "//div[@class='paginator']//span[contains(text(),'TEXTTOREPLACE')]"
MR_PROFILE_LOGS_PAGESIZE = "//select[@id='pageSize']//option[contains(text(),'TEXTTOREPLACE')]"
MR_PROFILE_LOGS_ENTRY_ITEMS = "//*[@id='log_list']//table//tbody//tr[*]"
MR_PROFILE_LOGS_ENTRY_ID = "//*[@id='log_list']//table//tbody//tr[TEXTTOREPLACE]//td[1]"
MR_PROFILE_LOGS_ENTRY_NAME = "//*[@id='log_list']//table//tbody//tr[TEXTTOREPLACE]//td[2]"

'''
@SCHEDULING 
'''
ENTRY_SCHEDULING = "//div[text()='Scheduling']"
SCHEDULING_SCHEDULED_RB = "//p-radiobutton[@value='scheduled']"
SCHEDULING_ANYTIME_RB = "//p-radiobutton[@value='anytime']"
SCHEDULING_STARTDATE_BTN = "//p-calendar[@formcontrolname='startDate']"
SCHEDULING_ENDDATE_CB = "//label[contains(text(),'End Date')]"
SCHEDULING_ENDDATE_BTN = "//p-calendar[@formcontrolname='endDate']"
SCHEDULING_STARTDATE_YEAR = "//option[@value='TEXTTOREPLACE']"
SCHEDULING_STARTDATE_MONTH = "//option[contains(text(),'TEXTTOREPLACE')]"
SCHEDULING_STARTDATE_DAY = "//table//tbody//tr[row]//td[col]"
SCHEDULING_STARTDATE_TEXT = "//p-calendar[@formcontrolname='startDate']//span//input"
SCHEDULING_ENDDATE_TEXT = "//p-calendar[@formcontrolname='endDate']//span//input"
SCHEDULING_SCHEDULED_CLOSE = "//i[@class='kIconclose_small kClose']"

'''
@ANALYTICS
'''
ANALYTICS_TAB = "//a[@class='kMenuLink ng-star-inserted' and contains(text(),'ANALYTICS')]"
ANALYTICS_BACK_BUTTON = "//i[@class='kIcondropdown_arrow_left']"
ANALYTICS_LOGO = "//i[@class='k-analytics-logo']"
ANALYTICS_MENU_ITEM = "//a[contains(@class,'ng-star-inserted') and contains(text(),'TEXTTOREPLACE')]"
ANALYTICS_SUBMENU_ITEM = "//div[contains(@class,'subMenuContainer')]//a[contains(text(),'TEXTTOREPLACE')]"
ANALYTICS_PAGE_TITLE = "//div[@class='kReportHeader']//span[@class='kTitle' and contains(text(),'TEXTTOREPLACE')]"
ANALYTICS_SELECTED_PERIOD = "//div[contains(@class,'ui-button ui-widget ui-state-default ui-button-text-only ng-star-inserted ui-state-active')]"
ANALYTICS_GRAPH_PERIOD_BUTTON = "//span[@class ='ui-button-text ui-clickable ng-star-inserted' and contains(text(),'TEXTTOREPLACE')]"
ANALYTICS_EXPORT_BUTTON = "//span[@class='ui-button-text ui-clickable' and contains(text(),'Export')]"
ANALYTICS_DATE_DROPDOWN = "//div[contains(@class,'datesRangeDropDown')]//span"
ANALYTICS_DATE_PRESET_OPTION = "//label[contains(@class,'ui-radiobutton-label') and text()='TEXTTOREPLACE']"
ANALYTICS_DATE_VIEW_OPTION = "//span[contains(@class,'ui-button-text ui-clickable ng-star-inserted') and text()='TEXTTOREPLACE']"
ANALYTICS_DATE_APPLY = "//span[@class='ui-button-text ui-clickable' and text()='Apply']"
ANALYTICS_DATE_COMPARE_CHECKBOX = "//label[contains(@class,'ng-star-inserted ui-chkbox-label') and text()='Compare with another period']"
ANALYTICS_DATE_COMPARE_OPTION = "//p-radiobutton[@name='compare' and @value='TEXTTOREPLACE']"
ANALYTICS_DATE_COMPARE_OPTION_RADIOBUTTON = "//p-radiobutton[@name='compare' and @value='TEXTTOREPLACE']//span[contains(@class,'ui-radiobutton-icon ui-clickable')]"
ANALYTICS_DATE_COMPARE_RADIOBUTTON_ON = ".//div[contains(@class,'ui-radiobutton-box') and contains(@class,'ui-state-active')]"
ANALYTICS_COMPARE_ICON = "//i[contains(@class,'compareIcon')]"
ANALYTICS_KMC_USER_MENU = "//div[contains(@class,'kUserName')]"
ANALYTICS_KMC_USER_SETTINGS = "//div[@class='kUserSettings']"
ANALYTICS_KMC_USER_SETTINGS_DROPDOWN = ".//label[contains(@class,'ui-dropdown-label ui-inputtext')]"
ANALYTICS_ICON_INPUT_CALENDAR = "//p-calendar[contains(@class,'ui-inputwrapper') and @icon='kIconcalendar']"
ANALYTICS_COMPARE_ICON_INPUT_CALENDAR = "//div[contains(@class,'kCompare')]//p-calendar[contains(@class,'ui-inputwrapper') and @icon='kIconcalendar']"
ANALYTICS_RANGE_CALENDAR = "//p-calendar[@selectionmode='range']"
ANALYTICS_ICON_CALENDAR_BUTTON = ".//span[contains(@class,'ui-button-icon-left ui-clickable kIconcalendar')]"
ANALYTICS_DATE_PICKER_MONTH_DROPDOWN = ".//select[contains(@class,'ui-datepicker-month')]"
ANALYTICS_DATE_PICKER_YEAR_DROPDOWN = ".//select[contains(@class,'ui-datepicker-year')]"
ANALYTICS_DATE_PICKER_DROPDOWN_OPTION = ".//option[@value='TEXTTOREPLACE']"
ANALYTICS_DATE_PICKER_DAY = ".//a[contains(@class,'ui-state-default') and text()='TEXTTOREPLACE']"
ANALYTICS_DATE_INPUT = ".//input[@type='text']"
ANALYTICS_DATE_WIDGET = "//div[contains(@class,'kPopupWidgetContent')]"
ANALYTICS_POPUP_WIDGET_OVERLAY = "//div[contains(@class,'kPopupWidgetModalOverlay')]"
ANALYTICS_REPORT_CONTENT = "//div[contains(@class,'kReportContent')]"
ANALYTICS_REPORT_CONTAINER = "//div[@class='kReportContainer']"
ANALYTICS_REPORT_SECTION_TITLE = ".//span[@class='kTitle']"
ANALYTICS_REPORT_TAB_NAME = ".//span[@class='kTabTitle']"
ANALYTICS_REPORT_TAB = "//div[contains(@class,'kTab')]//span[@class='kTabTitle' and contains(text(),'TAB_NAME')]"
ANALYTICS_REPORT_CHART = "//div[@class='kChart']"
ANALYTICS_GRAPH_CANVAS = ".//canvas"
ANALYTICS_GRAPH_TOOLTIP = ".//div[@class='kGraphTooltip']"
ANALYTICS_SUMMARY_SECTION = "//span[@class='kTitle' and text()='TITLE']/ancestor::div[@class='kReport kMini kOverrideFAIcons']"
ANALYTICS_HIGHLIGHTS_METRIC = "//div[@class='kVal']"
ANALYTICS_HIGHLIGHTS_METRIC_TITLE = ".//span[@class='title']"
ANALYTICS_HIGHLIGHTS_METRIC_VALUE = ".//span[contains(@class,'value')]"
ANALYTICS_HIGHLIGHTS_METRIC_VALUE_COMPARE_MODE = ".//span[contains(@class,'kTrend')]"
ANALYTICS_COMPARE_TOOLTIP = "//div[@class ='kTotalsCompareTooltip']"
ANALYTICS_COMPARE_TOOLTIP_DATE = ".//span[@class ='kTimePeriod']"
ANALYTICS_COMPARE_TOOLTIP_VALUE = ".//span[@class ='kTotalsCompareTooltipValue']"
ANALYTICS_HIGHLIGHTS_REPORT = "//div[@id='highlights-report']"
ANALYTICS_PAGER = ".//p-paginator"
ANALYTICS_PAGER_PAGE = ".//a[contains(@class,'ui-paginator-page ui-paginator-element')]"
ANALYTICS_PAGER_PAGE_NO = ".//a[contains(@class,'ui-paginator-page ui-paginator-element') and text()='TEXTTOREPLACE']"
ANALYTICS_PAGER_FIRST = ".//a[contains(@class,'ui-paginator-first')]"
ANALYTICS_PAGER_LAST = ".//a[contains(@class,'ui-paginator-last')]"
ANALYTICS_PAGER_PREV = ".//a[contains(@class,'ui-paginator-prev')]"
ANALYTICS_PAGER_NEXT = ".//a[contains(@class,'ui-paginator-next')]"
ANALYTICS_PAGER_ACTIVE_PAGE = ".//a[contains(@class,'ui-paginator-page') and contains(@class,'ui-state-active')]"
ANALYTICS_TABLE_TOGGLE = ".//div[@class='kToggle']//a[contains(text(),'TEXTTOREPLACE')]"
ANALYTICS_TABLE_HEADERS = ".//table/thead/tr/th"
ANALYTICS_TABLE_ROWS = ".//table/tbody/tr"
ANALYTICS_TABLE_ROW_COLUMNS = ".//td"
ANALYTICS_HIGHLIGHTS_REPORT = "//div[@class='kChart ng-star-inserted']"
ANALYTICS_LOADING = "//span[text()='Loading...']"
ANALYTICS_ICON_MINUS = ".//i[contains(@class,'icon-minus')]"
ANALYTICS_ICON_PROGRESS = ".//i[contains(@class,'icon-progress')]"
ANALYTICS_ICON_REGRESSION = ".//i[contains(@class,'icon-regression')]"
ANALYTICS_TREND_LABEL = ".//span[contains(@class,'kTrend')]"
ANALYTICS_TITLE_HELP_TOOLTIP_ICON = "//span[@class='kTitle' and text()='TITLE']/following-sibling::kinputhelper/descendant::div[@class='kInputHelper']"
ANALYTICS_SUB_TITLE_HELP_TOOLTIP_ICON = "//span[@class='kTabTitle' and text()='TITLE']/following-sibling::kinputhelper/descendant::div[@class='kInputHelper']"
ANALYTICS_HELP_TOOLTIP_CONTENT = "//div[@class='kInputHelperPopupContent']"
ANALYTICS_REPORT_HEADER = "//div[@class='kReportHeader']"
ANALYTICS_TOP_VIDEOS_HIGHLIGHTS_ROW = "//div[@class='kReportRow ng-star-inserted']"
ANALYTICS_TOP_VIDEOS_INDEX = ".//div[contains(@class,'kReportRowIndex')]"
ANALYTICS_TOP_VIDEOS_TABLE_ROW_BY_INDEX = ".//div[contains(@class,'kReportRowIndex')]/descendant::span[text()='INDEX']/ancestor::tr[contains(@class,'kTopVideoRow')]"
ANALYTICS_TOP_VIDEOS_SCORE = ".//span[@class='kScore']"
ANALYTICS_TOP_VIDEOS_TABLE = "//div[@id='top-videos']"
ANALYTICS_TOP_VIDEOS_TABLE_ROW = "//tr[contains(@class,'kTopVideoRow')]"
ANALYTICS_TOP_VIDEOS_TABLE_ENTRY_NAME = ".//span[@class='kTableColumn kEntryName']"
ANALYTICS_TOP_VIDEOS_TABLE_SCORE = ".//td[@class='kScore']"
ANALYTICS_TOP_VIDEOS_COMPARE_TABLES = ".//div[contains(@class,'kTableContainer')]"
ANALYTICS_TOP_VIDEOS_DATES = ".//span[contains(@class,'kDates')]"
ANALYTICS_EXIT_COMPARE = "//a[contains(@class,'kExitCompare')]"
ANALYTICS_ACCUMULATIVE_TITLE = ".//span[class='kAccumulativeTitle']"
ANALYTICS_ACCUMULATIVE_ITEM_TITLE = ".//div[contains(@class,'kItem')]//span[@class='kLabel']"
ANALYTICS_ACCUMULATIVE_ITEM_VALUE = ".//div[contains(@class,'kItem')]//div[@class='kValueContainer']"
ANALYTICS_TABLE_DIMENSION_MENU = ".//p-dropdown"
ANALYTICS_TABLE_SELECT_MENU_OPTION = ".//li[contains(@aria-label,'TEXTTOREPLACE')]"

'''
@LOGIN_ZOOM
'''
ZOOM_LOGIN_USER = "//input[contains(@name,'email')]"
ZOOM_LOGIN_PASS = "//input[contains(@name,'password')]"
ZOOM_LOGIN_SUBMIT = "//a[text()='Sign In']"
ZOOM_LOGIN_SUBMIT2 = "//button[text()='Sign In']"
ZOOM_MEETINGS_TAB = "//a[text()='Meetings']"
ZOOM_DROPDOWN_HOSTMEETING = "//div[@id='dropdown-hostmeeting']"
ZOOM_WITH_VIDEO_ON = "//a[@role='menuitem' and contains(text(),'With Video On')]"
ZOOM_START_SENDING_MY_VIDEO = "//a[contains(text(),'start from your browser')]"
ZOOM_RECORD = "//span[text()='Record']"
ZOOM_STOP_RECORDING = "//span[text()='Stop Recording']"
ZOOM_DIALOG_YES = "//button[text()='Yes']"
ZOOM_LEAVE_MEETING = "//button[text()='Leave Meeting']"
ZOOM_DIALOG_END_MEETING = "//button[text()='End Meeting']"
ZOOM_START_THIS_MEETING_BTN = "//button[text()='Start this Meeting']"
ZOOM_SIGNIN_TO_START_BTN = "//a[text()='Sign in to Start']"
ZOOM_DIALOG_LEAVE_MEETING = "//div[contains(@class,'zm-modal-footer-default-actions')]"
ZOOM_REGISTRATION_AUTHORIZE = "//span[text()='Authorize']"
ZOOM_REGISTRATION_DECLINE = "//span[text()='Decline']"
ZOOM_REGISTRATION_PARTNER_NAME = "//input[contains(@name,'uname')]"
ZOOM_REGISTRATION_PARTNER_PWD = "//input[contains(@name,'pwd')]"
ZOOM_REGISTRATION_PARTNER_ID = "//input[contains(@name,'partnerId')]"
ZOOM_REGISTRATION_LOGIN_BTN = "//button[text()='Login']"
ZOOM_REGISTRATION_DEFAULT_USERID = "//input[contains(@name,'defaultUserId')]"
ZOOM_REGISTRATION_CATEOGRY = "//input[contains(@name,'zoomCategory')]"
ZOOM_REGISTRATION_WEBINAR_CATEOGRY = "//input[contains(@name,'zoomWebinarCategory')]"
ZOOM_REGISTRATION_USER_POSTFIX = "//input[contains(@name,'zoomUserPostfix')]"
ZOOM_REGISTRATION_ENABLE_RECORDINGUPLOAD = "//input[contains(@class,'enableRecordingUpload')]"
ZOOM_REGISTRATION_ENABLE_CREATE_USERIDIFNOTEXIST = "//input[contains(@class,'createUserIfNotExist')]"
ZOOM_REGISTRATION_ENABLE_RECORDINGWEBINARUPLOAD = "//input[contains(@class,'enableWebinarUpload')]"
ZOOM_REGISTRATION_PARTICIPANT_HANDLER = "//input[@name='participantHandler' and @value='TEXTTOREPLACE']"
ZOOM_REGISTRATION_USERMATCHING_HANDLER = "//input[@name='userMatchingHandler' and @value='TEXTTOREPLACE']"
ZOOM_REGISTRATION_SUBMIT_BTN = "//button[text()='Submit']"
ZOOM_REGISTRATION_ALERT_SUCCESS = "//p[contains(text(),'Saved Successfully')]"
ZOOM_REGISTRATION_ALERT_FAIL = "//p[contains(text(),'Data was Not Saved')]"

'''
@KMC_ACCOUNT
'''
KMC_USER_NAME = "//div[@class='kUserName']"
KMC_CHANGE_ACCOUNT_BTN = "//a[text()='Change Account']"
KMC_ACCOUNT_NAME = "//label[text()='TEXTTOREPLACE']"
KMC_ACCOUNT_CLOSE_BTN = "//i[contains(@class,'kIconclose_small')]"
KMC_ACCOUNT_CONTINUE_BTN = "//span[text()='Continue']"
KMC_WHATSNEW = "//div[contains(@class,'whatsNew')]"

'''
@SIP
'''
SIP_INVITE_BTN = "//button[text()='Invite']"
SIP_MANAGE_PARTICIPANTS_BTN = "//span[text()='Manage Participants']"
SIP_INVITE_ROOM_SYSTEM = "//span[text()='Room System']"
SIP_INVITE_CALL_OUT = "//button[text()='Call Out']"
SIP_RB = "//span[text()='SIP']"
SIP_IP_ADDRESS = "//input[contains(@placeholder,'IP address')]"
SIP_CALL_BTN = "//button[text()='Call']"
SIP_INVAITE_CLOSE_BTN = "//button[contains(@aria-label,'Close')]"
ZOOM_DIALOG_CLOSE = "//button[contains(@aria-label,'close')]"
SIP_RING_STATUS = "//div[text()='Ring']"
SIP_FAILD_STATUS = "//div[text()='Failed']"

'''
@PAGINATION
'''
FIRST_PAGE = "//span[@class='p-paginator-icon pi pi-angle-double-left']"
LAST_PAGE = "//span[@class='p-paginator-icon pi pi-angle-double-right']"
NEXT_PAGE = "//span[@class='p-paginator-icon pi pi-angle-right']"
PREV_PAGE = "//span[@class='p-paginator-icon pi pi-angle-left']"
# PAGE_NUMBER = "//button[@class='p-paginator-page p-paginator-element p-link p-ripple']"
PAGE_NUMBER = "//button[contains(@class,'p-paginator-page p-paginator-element p-link')]"
ROWS_MENU = "//span[@class='p-dropdown-trigger-icon pi pi-chevron-down']"
MENU_ROW_OPTION = "//li[contains(@class,'p-dropdown-item')]"
DISABLED_FIRST_PAGE = "//button[@class='p-paginator-first p-paginator-element p-link p-disabled p-ripple']"
DISABLED_LAST_PAGE = "//button[@class='p-paginator-last p-paginator-element p-link p-ripple  p-disabled']"
DISABLED_NEXT_PAGE = "//button[@class='p-paginator-next p-paginator-element p-link p-ripple p-disabled']"
DISABLED_PREV_PAGE = "//button[@class='p-paginator-prev p-paginator-element p-link p-disabled p-ripple']"

'''
@LIVE_DASHBOARD
'''
LIVE_FILTER_STOPPED_CHANELS                                     = "//span[contains(text(),'Filter Stopped Channels')]"
LIVE_DASHBOARD_TAB                                              = "//div[contains(@title,'TEXTTOREPLACE')]"
LIVE_DASHBOARD_ENTRYID                                          = "//tr[contains(@class,'MuiTableRow-root')]//td[contains(text(),'TEXTTOREPLACE')]"
LIVE_DASHBOARD_ROWS                                             = "//tr[contains(@class,'MuiTableRow-root')]"
LIVE_DASHBOARD_SEARCH_ENTRYID                                   = "//div[contains(@class,'MuiGrid-root')]//input[contains(@class,'MuiInputBase-input')]"
LIVE_DASHBOARD_ENTRY_DRILLDOWN_OUTPUTS_TABLE                    ="//table[contains(@class,'MuiTable-root')]//tr[contains(@class,'MuiTableRow-root')]//td[contains(@class,'MuiTableCell-root MuiTableCell-body')]"




class DomManipulate:

    def replaceValInXpath(self, baseStr, findWaht, replce):
        return baseStr.replace(findWaht, replce)



